# Generated by Django 5.0.3 on 2024-04-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs348web', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title'], name='cs348web_bo_title_e6c819_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['author'], name='cs348web_bo_author_3efc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='bookcopy',
            index=models.Index(fields=['status'], name='library_boo_status_52a709_idx'),
        ),
        migrations.AlterModelTable(
            name='bookcopy',
            table='library_book',
        ),
    ]
