# Generated by Django 5.0.3 on 2024-04-26 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs348web', '0002_book_cs348web_bo_title_e6c819_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='bookcopy',
            new_name='library_boo_status_fb9309_idx',
            old_name='library_boo_status_52a709_idx',
        ),
        migrations.AlterModelTable(
            name='bookcopy',
            table='library_bookcopy',
        ),
    ]
